[[header]]
:description: RISC-V IOMMU Specification Document
:company: RISC-V.org
:revdate: 10/2022
:revnumber: 0.9
:revremark: This document is in development. Assume everything can change. See http://riscv.org/spec-state for details.
:url-riscv: http://riscv.org
:doctype: book
:preface-title: Preamble
:colophon:
:appendix-caption: Appendix
:imagesdir: images
:title-logo-image: image:risc-v_logo.svg[pdfwidth=3.25in,align=center]
// Settings:
:experimental:
:reproducible:
// needs to be changed? bug discussion started
//:WaveDromEditorApp: app/wavedrom-editor.app
:imagesoutdir: images
:bibtex-file: iommu.bib
:bibtex-order: appearance
:bibtex-style: ieee
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:toc: left
:toclevels: 4
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]
:data-uri:
:hide-uri-scheme:
:stem: latexmath
:footnote:
:xrefstyle: short

= RISC-V IOMMU Specification Document
IOMMU Task Group

////
TAKEN AS-IS from iommu_intro.adoc
Please in ditaa figures don't use the minus key '-' in your keyboard when
typing text (like 'non-privileged' in the figure below).
'-' is a special character that is used by ditaa to draw lines, not text.
Instead use a different unicode character that looks similar.
The figure below uses the unicode character with code U+2212 instead of the '-'
character of your keyboard (which has the unicode code U+002B).
Note that in your editor both probably look the same, but when rendered by
ditaa/asciidoc the '-' from your keyboard is used to draw a line, while the
alternative looks as a minus symbol.
If you don't know how to type an unicode character in your editor you might
simply copy the '−' character in the 'non−privileged' word from the drawing
below.
Other potential unicode characters might be found in the following links:
- https://www.compart.com/en/unicode/category/Pd
- https://www.compart.com/en/unicode/bidiclass/ES
////

[[fig:trace-topo-single]]
.Simplest trace: Single Hart, Trace Encoder and Trace Sink/Bridge
["ditaa",shadows=false, separation=false, fontsize: 14]
....
+----------------+
| Single Hart    |
|         +----------+    +---------+     +------------+ 
|         |  Trace   |    |  Trace  |     | Trace Sink |
|         | Ingress =====>| Encoder |---->|    or      |
|         |  Port    |    |         |     | ATB Bridge |
|         +----------+    +---------+     +------------+
|                |
+----------------+
....

[[fig:trace-topo-multi]]
.Multi-hart trace: Three harts, three Encoders, single Funnel and single Sink/Bridge
["ditaa",shadows=false, separation=false, fontsize: 14]
....
+-----------+   +---------+
| Hart with |   |  Trace  |
| Ingress   |==>| Encoder |---+
|  Port     |   |         |   |
+-----------+   +---------+   |
                              |
+-----------+   +---------+   |   +--------+     +-------------+ 
| Hart with |   |  Trace  |   +-->| Trace  |     | Trace Sink  |
| Ingress   |==>| Encoder |------>| Funnel |---->|    or       |
|  Port     |   |         |   +-->|        |     | ATB Bridge  |
+-----------+   +---------+   |   +--------+     +-------------+
                              |
+-----------+   +---------+   |
| Hart with |   |  Trace  |   |
| Ingress   |==>| Encoder |---+
|  Port     |   |         |
+-----------+   +---------+
....

[[fig:trace-topo-clusters]]
.Multi-cluster trace: two three-hart clusters with top-level Funnel and Sink/Bridge  
["ditaa",shadows=false, separation=false, fontsize: 14]
....
+-------------------------+
| 3 Harts with 3 Encoders |
|   and local Funnel      |---+
|       (see above)       |   | 
+-------------------------+   |
                              |   +--------+     +-------------+ 
                              +-->| Trace  |     | Trace Sink  |
                                  | Funnel |---->|    or       |
                              +-->| (top)  |     | ATB Bridge  |
                              |   +--------+     +-------------+
+-------------------------+   |
| 3 Harts with 3 Encoders |   | 
|   and local Funnel      |---+
|       (see above)       |
+-------------------------+
....

[[fig:trace-topo-mixed]]
.Local RAM Sink: Three-hart cluster plus extra hart with own RAM Sink (in SRAM mode)
["ditaa",shadows=false, separation=false, fontsize: 14]
....
+-------------------------+
| 3 Harts with 3 Encoders |
|     and local Funnel    |---+
|       (see above)       |   | 
+-------------------------+   |
                              |
+-----------+   +---------+   |   +--------+     +-------------+ 
| Hart with |   |  Trace  |   +-->| Trace  |     | Trace Sink  |
| Ingress   |==>| Encoder |------>| Funnel |---->|    or       |
|  Port     |   |         |---+   | (top)  |     | ATB Bridge  |
+-----------+   +---------+   |   +--------+     +-------------+
                              |
                              v
                      +----------------+ 
                      | Trace RAM Sink |
                      | (in SRAM mode) |
                      +----------------+ 
....

// Preamble
[WARNING]
.This document is in the link:http://riscv.org/spec-state[Development state]
====
Assume everything can change. This draft specification will change before 
being accepted as standard, so implementations made to this draft 
specification will likely not conform to the future standard.
====

[preface]
== Copyright and license information
This specification is licensed under the Creative Commons 
Attribution 4.0 International License (CC-BY 4.0). The full 
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2022 by RISC-V International.

////

//[preface]
//include::contributors.adoc[]

//include::iommu_intro.adoc[]
//include::iommu_data_structures.adoc[]
//include::iommu_in_memory_queues.adoc[]
include::iommu_debug.adoc[]
include::iommu_registers.adoc[]
include::iommu_sw_guidelines.adoc[]
include::iommu_hw_guidelines.adoc[]
//the index must precede the bibliography
//include::index.adoc[]
include::bibliography.adoc[]

////
